### ISSUE TITLE
ftop recalc/reload issues

### ISSUE THREAD

**Issue by ntkohrt** [novucs/factions-top#117]
Running 1.13.2

Plugin version 1.2.0

Plugin runs fine, calculates all blocks, player balances and spawners just fine.

My issue is, it very rarely recalculates. It doesn't on schedule, and it doesn't with running either command or even rebooting the server. I haven't been able to figure out when or why it refreshes when it does but it's only every couple days. Any tips or fixes?

**Comment by novucs** [comment]
Ideally it will never fully recalculate, and recalculations are not scheduled from within the plugin. I imagine you are executing the recalculate task elsewhere. This plugin is very efficient in how it handles the ftop leaderboard as it relies entirely on events. A nice side effect of this major efficiency boost is that it calculates the worth immediately, providing realtime statistics, meaning there is no need for computationally expensive full recalculate tasks.

**Comment by ntkohrt** [comment]
Thank you for the response, I understand everything you’ve said but I don’t think I explained my situation enough. It goes days without updating even a single dollar. For example, a faction has 93 blaze spawners listed on /f top. Around a week ago they placed 150 more but the leaderboard hasn’t changed. Usually it does update after a day or two but as I mentioned it’s nearing a week so I’ve contacted you. I remember seeing something about these events, where can I find more information?

**Comment by novucs** [comment]
If you are having difficulty with events not being registered, check your configuration matches that of the default here:

```
  perform-recalculate:
    command: true
    unload: true
    claim: true
    break: true
    place: true
    explode: true
    chest: true
  bypass-recalculate-delay:
    command: true
    unload: true
    claim: true
    break: false
    place: false
    explode: false
    chest: false
```
